### ISSUE TITLE
Build `latest` tag each time ModuleSync main branch changes

### ISSUE THREAD

**Issue by bittner** [vshn/docker-modulesync#11]
The `latest` tag of this image promises to reflect the state of the ModuleSync repository HEAD, [according to the README](https://github.com/vshn/docker-modulesync#supported-tags).

Currently, `latest` is on par with version 2.0.0, but [version 2.0.1](https://rubygems.org/gems/modulesync/versions/2.0.1) was released late last year, and the main branch has advanced, too. It would be nice to have an automated mechanism in place that monitors the ModuleSync repository and triggers the related build on Docker Hub.

For now, could you simply trigger a build for `latest` now on Docker Hub? This way we could benefit from the latest changes, even though v2.0.1 is not yet reflected in this project.

## What else?

Alternatively, and maybe technically superior and simpler as a solution, you may ask @voxpupuli to configure a webhook that triggers the build on Docker Hub. In this case, it would probably make sense to ask them to take over maintenance of the container image as such, in the long run at least.

Heads-up @ekohl and @bastelfreak

**Comment by mhutter** [comment]
Fixed in #12; Renovate will update the Dockerfile when there is a new release, and `latest` just tracks the latest release.

**Comment by bittner** [comment]
Manuel, you are the best! :1st_place_medal:
